### ISSUE TITLE
Your WSDL homework is not working

### ISSUE THREAD

**Issue by jakubklimek** [skrhakv/NSWI145#1]
But you already know that. You have until the next deadline to add it.

The reason the schema does not work can be seen when comparing it to the generated one or simply by seeing in SoapUI what is being sent to the service. It is RPC-style, so it expects the `arg0`, `arg1` etc. elements for arguments, which are nowhere to be found in your XSD.

**Comment by skrhakv** [comment]
Strange, because the WSDL was working on my machine - it loaded the generated-one XSD file:
```
...
<xsd:import namespace="http://soap02/" schemaLocation="http://127.0.0.1:8000/BankService?xsd=1"/>
...
```
So when I sent a request using SoapUI, the request returned a valid response.

However I have created a new commit with XSD written by hand, so I assume it should be working now just fine (it is working on my machine at least). Please take a look and let me know if any problem occurs.
